<%
' FP_ASP ASP Automatically generated by a Frontpage Component. Do not Edit.
On Error Resume Next
Session("FP_OldCodePage") = Session.CodePage
Session("FP_OldLCID") = Session.LCID
Session.CodePage = 1252
Err.Clear

strErrorUrl = ""

If Request.ServerVariables("REQUEST_METHOD") = "POST" Then
If Request.Form("VTI-GROUP") = "0" Then
	Err.Clear

	Set fp_conn =  Server.CreateObject("ADODB.Connection")
	FP_DumpError strErrorUrl, "Cannot create connection"

	Set fp_rs = Server.CreateObject("ADODB.Recordset")
	FP_DumpError strErrorUrl, "Cannot create record set"

	fp_conn.Open Application("armored-registry-database_ConnectionString")
	FP_DumpError strErrorUrl, "Cannot open database"

	fp_rs.Open "Results", fp_conn, 1, 3, 2 ' adOpenKeySet, adLockOptimistic, adCmdTable
	FP_DumpError strErrorUrl, "Cannot open record set"

	fp_rs.AddNew
	FP_DumpError strErrorUrl, "Cannot add new record set to the database"
	Dim arFormFields0(13)
	Dim arFormDBFields0(13)
	Dim arFormValues0(13)

	arFormFields0(0) = "StreetAddress"
	arFormDBFields0(0) = "StreetAddress"
	arFormValues0(0) = Request("StreetAddress")
	arFormFields0(1) = "Period"
	arFormDBFields0(1) = "Period"
	arFormValues0(1) = Request("Period")
	arFormFields0(2) = "Division"
	arFormDBFields0(2) = "Division"
	arFormValues0(2) = Request("Division")
	arFormFields0(3) = "Company"
	arFormDBFields0(3) = "Company"
	arFormValues0(3) = Request("Company")
	arFormFields0(4) = "Regiment"
	arFormDBFields0(4) = "Regiment"
	arFormValues0(4) = Request("Regiment")
	arFormFields0(5) = "City"
	arFormDBFields0(5) = "City"
	arFormValues0(5) = Request("City")
	arFormFields0(6) = "FirstName"
	arFormDBFields0(6) = "FirstName"
	arFormValues0(6) = Request("FirstName")
	arFormFields0(7) = "EmailAddress"
	arFormDBFields0(7) = "EmailAddress"
	arFormValues0(7) = Request("EmailAddress")
	arFormFields0(8) = "ZipCode"
	arFormDBFields0(8) = "ZipCode1"
	arFormValues0(8) = Request("ZipCode")
	arFormFields0(9) = "MI"
	arFormDBFields0(9) = "MI"
	arFormValues0(9) = Request("MI")
	arFormFields0(10) = "LastName"
	arFormDBFields0(10) = "LastName"
	arFormValues0(10) = Request("LastName")
	arFormFields0(11) = "State"
	arFormDBFields0(11) = "State"
	arFormValues0(11) = Request("State")
	arFormFields0(12) = "Comments"
	arFormDBFields0(12) = "Comments1"
	arFormValues0(12) = Request("Comments")

	FP_SaveFormFields fp_rs, arFormFields0, arFormDBFields0

	If Request.ServerVariables("HTTP_USER_AGENT") <> "" Then
		FP_SaveFieldToDB fp_rs, Request.ServerVariables("HTTP_USER_AGENT"), "Browser_type"
	End If
	If Request.ServerVariables("REMOTE_HOST") <> "" Then
		FP_SaveFieldToDB fp_rs, Request.ServerVariables("REMOTE_HOST"), "Remote_computer_name"
	End If
	FP_SaveFieldToDB fp_rs, Now, "Timestamp"
	If Request.ServerVariables("REMOTE_USER") <> "" Then
		FP_SaveFieldToDB fp_rs, Request.ServerVariables("REMOTE_USER"), "User_name"
	End If

	fp_rs.Update
	FP_DumpError strErrorUrl, "Cannot update the database"

	fp_rs.Close
	fp_conn.Close

	FP_FormConfirmation "text/html; charset=windows-1252",_
						"Form Confirmation",_
						"Thank you for submitting the following information:",_
						"armored_registry.asp",_
						"Return to the form."

End If
End If

Session.CodePage = Session("FP_OldCodePage")
Session.LCID = Session("FP_OldLCID")

%>
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>2nd Armored Division Registry</title>
<meta name="Microsoft Border" content="none, default">
</head>

<body stylesrc="../index.html"><table border="0" width="100%">
  <tr>
    <td align="center"><b><font face="Verdana"><img src="../images/patch2.gif" alt="2nd Armored Emblem" align="left" hspace="5"></font></b></td>
    <td align="center">
      <h1><font face="Verdana">Armored Registry</font></h1>
    </td>
    <td align="center"><b><font face="Verdana"><img src="../images/tank2.gif" alt="2nd Armored Tank Logo" align="right" hspace="5" width="79" height="77"></font></b></td>
  </tr>
</table>
<p align="center"><font face="Verdana">This registry database is for former
members of any U.S. Army Armored Division from all periods and units to list
contact information for those who are looking to contact their fellow GIs.
Please include first and last name, address, or email address. (Please send any
change in email address to the <b>webmaster</b>.)</font></p>
<form method="POST" action="armored_registry.asp" webbot-action="--WEBBOT-SELF--">
  <!--webbot bot="SaveDatabase" startspan SuggestedExt="asp"
  U-ASP-Include-Url="../_fpclass/fpdbform.inc"
  S-DataConnection="armored-registry-database" S-RecordSource="Results"
  U-Database-URL="fpdb/armored_center_registry.mdb"
  S-Builtin-Fields="HTTP_USER_AGENT REMOTE_HOST Timestamp REMOTE_USER"
  S-Builtin-DBFields="Browser_type Remote_computer_name Timestamp User_name"
  S-Form-Fields="StreetAddress Period Division Company Regiment City FirstName EmailAddress ZipCode MI LastName State Comments"
  S-Form-DBFields="StreetAddress Period Division Company Regiment City FirstName EmailAddress ZipCode1 MI LastName State Comments1" --><input TYPE="hidden" NAME="VTI-GROUP" VALUE="0"><!--#include file="../_fpclass/fpdbform.inc"--><!--webbot
  bot="SaveDatabase" endspan i-checksum="34604" --><table border="0" cellpadding="0" cellspacing="6" width="480">
    <tr>
      <td width="95"></td>
      <td width="363"><font face="Verdana">Please disable your caps lock before
        completing the form below. <i><font color="#008000">You have the option
        of using only the street address field or email field or both.</font></i>
        Please fill out the rest of the form completely (Comment section is
        optional). Any submitted information that is incomplete or not related
        to this registry will be deleted. Thank you.</font></td>
    </tr>
    <tr>
      <td align="right" width="95"><font face="Verdana">First Name:</font></td>
      <td width="363"><font face="Verdana"><!--webbot bot="Validation"
        s-display-name="FirstName" b-value-required="TRUE" --><input type="text" size="30" name="FirstName"></font></td>
    </tr>
    <tr>
      <td align="right" width="95"><font face="Verdana">Middle Initial:</font></td>
      <td width="363"><font face="Verdana"><input type="text" name="MI" size="2"></font></td>
    </tr>
    <tr>
      <td align="right" width="95"><font face="Verdana">Last Name:</font></td>
      <td width="363"><font face="Verdana"><!--webbot bot="Validation"
        s-display-name="LastName" b-value-required="TRUE" --><input type="text" name="LastName" size="30"></font></td>
    </tr>
    <tr>
      <td align="right" width="458" colspan="2">
        <p align="left"><b><font face="Verdana">Contact Information:</font></b></td>
    </tr>
    <tr>
      <td align="right" width="95"><font face="Verdana" color="#008000">E-Mail
        Address:</font></td>
      <td width="363"><font face="Verdana"><input type="text" size="30" name="EmailAddress"></font></td>
    </tr>
    <tr>
      <td align="right" width="95"><b><i><font face="Verdana">and/or</font></i></b></td>
      <td width="363"><font face="Verdana">(one of these fields is required!)</font></td>
    </tr>
    <tr>
      <td align="right" width="95"><font face="Verdana"><font color="#008000">Street</font>
        <font color="#008000">Address:</font></font></td>
      <td width="363"><font face="Verdana"><input type="text" size="30" name="StreetAddress"></font></td>
    </tr>
    <tr>
      <td align="right" width="95"><font face="Verdana" color="#008000">City:</font></td>
      <td width="363"><font face="Verdana"><!--webbot bot="Validation"
        s-display-name="City" b-value-required="TRUE" --><input type="text" name="City" size="30"></font></td>
    </tr>
    <tr>
      <td align="right" width="95"><font face="Verdana"><font color="#008000">State/Province</font>:</font></td>
      <td width="363"><font face="Verdana"><!--webbot bot="Validation"
        s-display-name="State" b-value-required="TRUE"
        b-disallow-first-item="TRUE" --><select name="State" size="1">
          <option value="Select One" selected>Select One
          <option value="AL">Alabama
          <option value="AK">Alaska
          <option value="AZ">Arizona
          <option value="AR">Arkansas
          <option value="CA">Calif.
          <option value="CO">Colorado
          <option value="CT">Conn.
          <option value="DE">Delaware
          <option value="FL">Florida
          <option value="GA">Georgia
          <option value="HI">Hawaii
          <option value="ID">Idaho
          <option value="IL">Illinois
          <option value="IN">Indiana
          <option value="IA">Iowa
          <option value="KS">Kansas
          <option value="KY">Kentucky
          <option value="LA">Louisiana
          <option value="ME">Maine
          <option value="MD">Maryland
          <option value="MA">Mass.
          <option value="MI">Michigan
          <option value="MN">Minnesota
          <option value="MS">Miss.
          <option value="MO">Missouri
          <option value="MT">Montana
          <option value="NE">Nebraska
          <option value="NV">Nevada
          <option value="NH">New Hamp.
          <option value="NJ">New Jersey
          <option value="NM">New Mexico
          <option value="NY">New York
          <option value="NC">N. Carolina
          <option value="ND">N. Dakota
          <option value="OH">Ohio
          <option value="OK">Oklahoma
          <option value="OR">Oregon
          <option value="PA">Penn.
          <option value="RI">R. Island
          <option value="SC">S. Carolina
          <option value="SD">S. Dakota
          <option value="TN">Tennessee
          <option value="TX">Texas
          <option value="UT">Utah
          <option value="VT">Vermont
          <option value="VA">Virginia
          <option value="WA">Washington
          <option value="DC">Wash., D.C.
          <option value="WV">W. Virginia
          <option value="WI">Wisconsin
          <option value="WY">Wyoming
          <option value="AB">Alberta
          <option value="BC">Brit. Col.
          <option value="MB">Manitoba
          <option value="NB">New Bruns.
          <option value="NF">NF
          <option value="NS">Nova Scotia
          <option value="NT">NW Terr.
          <option value="ON">Ontario
          <option value="PE">P.E.I.
          <option value="PR">Puerto Rico</option>
          <option value="PQ">Quebec
          <option value="SK">Saskatch.
          <option value="YT">Yukon
        </select></font></td>
    </tr>
    <tr>
      <td align="right" width="95"><font face="Verdana" color="#008000">Zip Code:</font></td>
      <td width="363"><font face="Verdana"><!--webbot bot="Validation"
        S-Display-Name="ZipCode" S-Data-Type="Number" S-Number-Separators="x."
        --><input type="text" name="ZipCode" size="11"></font></td>
    </tr>
    <tr>
      <td align="right" width="95"><font face="Verdana">Division:</font></td>
      <td width="363"><font face="Verdana"><!--webbot bot="Validation"
        s-display-name="Division" b-value-required="TRUE" --><input type="text" size="10" name="Division"></font></td>
    </tr>
    <tr>
      <td align="right" width="95"><font face="Verdana">Regiment:</font></td>
      <td width="363"><font face="Verdana"><!--webbot bot="Validation"
        s-display-name="Regiment" b-value-required="TRUE" --><input type="text" name="Regiment" size="10"></font></td>
    </tr>
    <tr>
      <td align="right" width="95"><font face="Verdana">Company:</font></td>
      <td width="363"><font face="Verdana"><!--webbot bot="Validation"
        s-display-name="Company" b-value-required="TRUE" --><input type="text" name="Company" size="10"></font></td>
    </tr>
    <tr>
      <td align="right" width="95"><font face="Verdana">Period of Service in
        Armored Division:</font></td>
      <td width="363"><font face="Verdana"><!--webbot bot="Validation"
        s-display-name="Period" b-value-required="TRUE" --><input type="text" size="15" name="Period">example:
        1945-1947</font></td>
    </tr>
    <tr>
      <td align="right" width="95"><font face="Verdana">Comments:</font></td>
      <td width="363"><font face="Verdana"><textarea name="Comments" rows="5" cols="30"></textarea></font></td>
    </tr>
    <tr>
      <td width="95"><font face="Verdana">&nbsp;</font></td>
      <td width="363"><font face="Verdana"><input type="submit" value="Submit" name="Submit"><input type="reset" value="Reset" name="Reset"></font></td>
    </tr>
  </table>
</form>
<p align="center"><b><i><font face="Verdana">Back To: <a href="../index.html">2nd Armored Division HOME<br>
</a></font></i></b></p>
</body>

</html>
