<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a Frontpage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Armored Registry Search</title>
<meta name="Microsoft Border" content="none, default">
</head>

<body stylesrc="../index.html">

<form botid="0" method="POST" action="registry-search.asp">
  <div align="center">
    <center>
    <table border="0">
      <tr>
        <td colspan="2" align="center"><b><i><font face="Verdana">Search by...</font></i></b></td>
        <td align="center" rowspan="6" valign="middle"><font face="Verdana"><b><i>Search
          Suggestions:</i></b>&nbsp;</font></center>
        <ul type="square">
          <li>
            <p align="left"><font face="Verdana">If you are not sure of the
            spelling of the last name, just use the first letter of the last
            name to view all names that begin with that letter.&nbsp;</font></li>
          <li>
            <p align="left"><font face="Verdana">Using numerical values only for
            the Division and Regiment search will bring all results containing
            those numeric values. (example: &quot;2&quot; instead of
            &quot;2nd&quot; or &quot;2AD&quot;)</font></li>
        </ul>
      </td>
    </tr>
    <center>
    <tr>
      <td><b><font face="Verdana">Last Name:</font></b></td>
      <td><span style="text-transform: uppercase"><font face="Verdana"><input name="LastName" value="<%=Request("LastName")%>" size="20"></font></span></td>
    </tr>
    <tr>
      <td colspan="2" align="center"><b><i><font face="Verdana">or</font></i></b></td>
    </tr>
    <tr>
      <td><b><font face="Verdana">Division:</font></b></td>
      <td><span style="text-transform: uppercase"><font face="Verdana"><input name="Division" value="<%=Request("Division")%>" size="20"></font></span></td>
    </tr>
    <tr>
      <td colspan="2" align="center"><b><i><font face="Verdana">or</font></i></b></td>
    </tr>
    <tr>
      <td><b><font face="Verdana">Regiment:</font></b></td>
      <td><span style="text-transform: uppercase"><font face="Verdana"><input type="TEXT" name="Regiment" value="<%=Request("Regiment")%>" size="20"></font></span></td>
    </tr>
    </table>
    </center>
  </div>
  <p align="center"><font face="Verdana"><input type="Submit"><input type="Reset"><!--webbot
  bot="SaveAsASP" clientside suggestedext="asp" preview=" " startspan --><!--webbot bot="SaveAsASP" endspan --></font>
  <p>&nbsp;</p>
</form>
<div align="center">
  <center>
  <table bgcolor="#808000">
    <tbody>
      <!--webbot bot="DatabaseRegionStart" startspan
      s-columnnames="ID,FirstName,MI,LastName,EmailAddress,StreetAddress,City,State,ZipCode,Division,Regiment,Company,Period,Comments,Timestamp"
      s-columntypes="3,202,202,202,202,202,202,202,3,202,202,202,202,202,135"
      s-dataconnection="armored-registry-database" b-tableformat="TRUE"
      b-menuformat="FALSE" s-menuchoice="FirstName" s-menuvalue="FirstName"
      b-tableborder="FALSE" b-tableexpand="FALSE" b-tableheader="FALSE"
      b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="1"
      b-makeform="TRUE" s-recordsource="Results"
      s-displaycolumns="FirstName,MI,LastName,EmailAddress,StreetAddress,City,State,ZipCode,Division,Regiment,Company,Period,Comments"
      s-criteria="[LastName] BEG {LastName} | [Division] CNT {Division} | [Regiment] CNT {Regiment} |"
      s-order="[LastName] + [State] +"
      s-sql="SELECT * FROM Results WHERE (LastName LIKE '::LastName::%' OR Division LIKE '%::Division::%' OR Regiment LIKE '%::Regiment::%') ORDER BY LastName ASC,State ASC"
      b-procedure="FALSE" clientside suggestedext="asp"
      s-defaultfields="LastName=999&amp;amp;Division=999&amp;amp;Regiment=999"
      s-norecordsfound="No records returned." i-maxrecords="256" i-groupsize="5"
      botid="0" u-dblib="../_fpclass/fpdblib.inc" u-dbrgn1="../_fpclass/fpdbrgn1.inc"
      u-dbrgn2="../_fpclass/fpdbrgn2.inc" tag="TBODY"
      local_preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;Database Results regions will not preview unless this page is fetched from a Web server with a web browser. The following table row will repeat once for every record returned by the query.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;"
      preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;"
      b-wastableformat="TRUE" --><!--#include file="../_fpclass/fpdblib.inc"-->
<%
fp_sQry="SELECT * FROM Results WHERE (LastName LIKE '::LastName::%' OR Division LIKE '%::Division::%' OR Regiment LIKE '%::Regiment::%') ORDER BY LastName ASC,State ASC"
fp_sDefault="LastName=999&Division=999&Regiment=999"
fp_sNoRecords="<tr><td colspan=13 align=left width=""100%"">No records returned.</td></tr>"
fp_sDataConn="armored-registry-database"
fp_iMaxRecords=256
fp_iCommandType=1
fp_iPageSize=5
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice="FirstName"
fp_sMenuValue="FirstName"
fp_iDisplayCols=13
fp_fCustomQuery=False
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan -->
    </tbody>
  </table>
  </center>
</div>
<div align="center">
  <center>
  <table border="0" width="100%" bgcolor="#008000">
    <tr>
      <td valign="top" align="left"><font face="Verdana">Last Name:</font></td>
      <td bgcolor="#FFFFFF" valign="top" align="left"><span style="text-transform: uppercase"><font face="Verdana"><!--webbot
        bot="DatabaseResultColumn" startspan
        s-columnnames="ID,FirstName,MI,LastName,EmailAddress,StreetAddress,City,State,ZipCode,Division,Regiment,Company,Period,Comments,Timestamp"
        s-column="LastName" b-tableformat="TRUE" b-hashtml="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;LastName&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;LastName&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"LastName")%><!--webbot
        bot="DatabaseResultColumn" endspan --></font></span></td>
      <td valign="top" align="left"><font face="Verdana">First Name:</font></td>
      <td bgcolor="#FFFFFF" valign="top" align="left"><span style="text-transform: uppercase"><font face="Verdana"><!--webbot
        bot="DatabaseResultColumn" startspan
        s-columnnames="ID,FirstName,MI,LastName,EmailAddress,StreetAddress,City,State,ZipCode,Division,Regiment,Company,Period,Comments,Timestamp"
        s-column="FirstName" b-tableformat="TRUE" b-hashtml="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;FirstName&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;FirstName&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"FirstName")%><!--webbot
        bot="DatabaseResultColumn" endspan --></font></span></td>
      <td valign="top" align="left"><font face="Verdana">MI:</font></td>
      <td bgcolor="#FFFFFF" valign="top" align="left"><span style="text-transform: uppercase"><font face="Verdana"><!--webbot
        bot="DatabaseResultColumn" startspan
        s-columnnames="ID,FirstName,MI,LastName,EmailAddress,StreetAddress,City,State,ZipCode,Division,Regiment,Company,Period,Comments,Timestamp"
        s-column="MI" b-tableformat="TRUE" b-hashtml="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;MI&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;MI&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"MI")%><!--webbot
        bot="DatabaseResultColumn" endspan --></font></span></td>
    </tr>
    <tr>
      <td valign="top" align="left"><font face="Verdana">Email Address:</font></td>
      <td bgcolor="#FFFFFF" valign="top" align="left"><font face="Verdana"><!--webbot
        bot="DatabaseResultColumn" startspan
        s-columnnames="ID,FirstName,MI,LastName,EmailAddress,StreetAddress,City,State,ZipCode,Division,Regiment,Company,Period,Comments,Timestamp"
        s-column="EmailAddress" b-tableformat="TRUE" b-hashtml="FALSE"
        clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;EmailAddress&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;EmailAddress&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"EmailAddress")%><!--webbot
        bot="DatabaseResultColumn" endspan --></font></td>
      <td valign="top" align="left"><font face="Verdana">Street Address:</font></td>
      <td bgcolor="#FFFFFF" valign="top" align="left" colspan="3"><span style="text-transform: uppercase"><font face="Verdana"><!--webbot
        bot="DatabaseResultColumn" startspan
        s-columnnames="ID,FirstName,MI,LastName,EmailAddress,StreetAddress,City,State,ZipCode,Division,Regiment,Company,Period,Comments,Timestamp"
        s-column="StreetAddress" b-tableformat="TRUE" b-hashtml="FALSE"
        clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;StreetAddress&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;StreetAddress&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"StreetAddress")%><!--webbot
        bot="DatabaseResultColumn" endspan --></font></span></td>
    </tr>
    <tr>
      <td valign="top" align="left"><font face="Verdana">City:</font></td>
      <td bgcolor="#FFFFFF" valign="top" align="left"><span style="text-transform: uppercase"><font face="Verdana"><!--webbot
        bot="DatabaseResultColumn" startspan
        s-columnnames="ID,FirstName,MI,LastName,EmailAddress,StreetAddress,City,State,ZipCode,Division,Regiment,Company,Period,Comments,Timestamp"
        s-column="City" b-tableformat="TRUE" b-hashtml="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;City&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;City&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"City")%><!--webbot
        bot="DatabaseResultColumn" endspan --></font></span></td>
      <td valign="top" align="left"><font face="Verdana">State:</font></td>
      <td bgcolor="#FFFFFF" valign="top" align="left"><span style="text-transform: uppercase"><font face="Verdana"><!--webbot
        bot="DatabaseResultColumn" startspan
        s-columnnames="ID,FirstName,MI,LastName,EmailAddress,StreetAddress,City,State,ZipCode,Division,Regiment,Company,Period,Comments,Timestamp"
        s-column="State" b-tableformat="TRUE" b-hashtml="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;State&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;State&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"State")%><!--webbot
        bot="DatabaseResultColumn" endspan --></font></span></td>
      <td valign="top" align="left"><font face="Verdana">Zip Code:</font></td>
      <td bgcolor="#FFFFFF" valign="top" align="left"><font face="Verdana"><!--webbot
        bot="DatabaseResultColumn" startspan
        s-columnnames="ID,FirstName,MI,LastName,EmailAddress,StreetAddress,City,State,ZipCode,Division,Regiment,Company,Period,Comments,Timestamp"
        s-column="ZipCode" b-tableformat="TRUE" b-hashtml="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ZipCode&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ZipCode&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"ZipCode")%><!--webbot
        bot="DatabaseResultColumn" endspan --></font></td>
    </tr>
    <tr>
      <td valign="top" align="left"><font face="Verdana">Division:</font></td>
      <td bgcolor="#FFFFFF" valign="top" align="left"><span style="text-transform: uppercase"><font face="Verdana"><!--webbot
        bot="DatabaseResultColumn" startspan
        s-columnnames="ID,FirstName,MI,LastName,EmailAddress,StreetAddress,City,State,ZipCode,Division,Regiment,Company,Period,Comments,Timestamp"
        s-column="Division" b-tableformat="TRUE" b-hashtml="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Division&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Division&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Division")%><!--webbot
        bot="DatabaseResultColumn" endspan --></font></span></td>
      <td valign="top" align="left"><font face="Verdana">Regiment:</font></td>
      <td bgcolor="#FFFFFF" valign="top" align="left"><span style="text-transform: uppercase"><font face="Verdana"><!--webbot
        bot="DatabaseResultColumn" startspan
        s-columnnames="ID,FirstName,MI,LastName,EmailAddress,StreetAddress,City,State,ZipCode,Division,Regiment,Company,Period,Comments,Timestamp"
        s-column="Regiment" b-tableformat="TRUE" b-hashtml="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Regiment&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Regiment&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Regiment")%><!--webbot
        bot="DatabaseResultColumn" endspan --></font></span></td>
      <td valign="top" align="left"><font face="Verdana">Company:</font></td>
      <td bgcolor="#FFFFFF" valign="top" align="left"><span style="text-transform: uppercase"><font face="Verdana"><!--webbot
        bot="DatabaseResultColumn" startspan
        s-columnnames="ID,FirstName,MI,LastName,EmailAddress,StreetAddress,City,State,ZipCode,Division,Regiment,Company,Period,Comments,Timestamp"
        s-column="Company" b-tableformat="TRUE" b-hashtml="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Company&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Company&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Company")%><!--webbot
        bot="DatabaseResultColumn" endspan --></font></span></td>
    </tr>
    <tr>
      <td valign="top" align="left"><font face="Verdana">Period:</font></td>
      <td bgcolor="#FFFFFF" valign="top" align="left" colspan="5"><span style="text-transform: uppercase"><font face="Verdana"><!--webbot
        bot="DatabaseResultColumn" startspan
        s-columnnames="ID,FirstName,MI,LastName,EmailAddress,StreetAddress,City,State,ZipCode,Division,Regiment,Company,Period,Comments,Timestamp"
        s-column="Period" b-tableformat="TRUE" b-hashtml="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Period&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Period&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Period")%><!--webbot
        bot="DatabaseResultColumn" endspan --></font></span></td>
    </tr>
    <tr>
      <td colspan="6" bgcolor="#008000" valign="top" align="left"><font face="Verdana">Comments:</font></td>
    </tr>
    <tr>
      <td colspan="6" bgcolor="#FFFFFF" valign="top" align="left"><span style="text-transform: uppercase"><font face="Verdana"><!--webbot
        bot="DatabaseResultColumn" startspan
        s-columnnames="ID,FirstName,MI,LastName,EmailAddress,StreetAddress,City,State,ZipCode,Division,Regiment,Company,Period,Comments,Timestamp"
        s-column="Comments" b-tableformat="TRUE" b-hashtml="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Comments&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Comments&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Comments")%><!--webbot
        bot="DatabaseResultColumn" endspan --></font></span></td>
    </tr>
  </table>
  </center>
</div>
<font face="Verdana"><br>
</font>
<div align="center">
  <center>
  <table bgcolor="#808000">
    <tbody>
      <!--webbot bot="DatabaseRegionEnd" startspan b-tableformat="TRUE"
      b-menuformat="FALSE" u-dbrgn2="../_fpclass/fpdbrgn2.inc" i-groupsize="5"
      clientside tag="TBODY"
      local_preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;TR&gt;&lt;TD ALIGN=LEFT VALIGN=MIDDLE COLSPAN=64&gt;&lt;FORM&gt;&lt;NOBR&gt;&lt;INPUT TYPE=Button VALUE=&quot;  |&lt;  &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;   &lt;  &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;  &gt;   &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;  &gt;|  &quot;&gt;  [1/5]&lt;/NOBR&gt;&lt;/FORM&gt;&lt;/td&gt;&lt;/tr&gt;"
      preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;TR&gt;&lt;TD ALIGN=LEFT VALIGN=MIDDLE COLSPAN=64&gt;&lt;NOBR&gt;&lt;INPUT TYPE=Button VALUE=&quot;  |&lt;  &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;   &lt;  &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;  &gt;   &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;  &gt;|  &quot;&gt;  [1/5]&lt;/NOBR&gt;&lt;BR&gt;&lt;/td&gt;&lt;/tr&gt;" --><!--#include file="../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan -->
    </tbody>
  </table>
  </center>
</div>
&nbsp;</body>

</html>
